# Services definition override for CI/CD

services:

  app:
    # Build override
    image: ${IMAGES_PREFIX:-app}-cicd:${DOCKER_TAG:-latest}
    build:
      target: app_prod_build
    # Deploy override
    command: [ "sh", "-c", "rm -rf /tmp/dist/* && cp -r /app/dist/* /tmp/dist" ]
    volumes:
      - ./app/dist:/tmp/dist
