version: '3.4'

# Services definition for building & deploying

services:

  app:
    # Build
    image: ${IMAGES_PREFIX:-app}:${DOCKER_TAG:-latest}
    build:
      context: ./app
      dockerfile: ./Dockerfile
      target: app_prod
      args:
        PORT: ${HTTP_DOCKER_PORT:-80}
        GITHUB_REPOSITORY_URL: ${GITHUB_REPOSITORY_URL:-}
        GITHUB_SHA: ${GITHUB_SHA:-}
    # Deploy
    ports:
      - ${HTTP_PORT:-80}:${HTTP_DOCKER_PORT:-80} # HTTP
